apiVersion: v1
kind: Pod
metadata:
  name: httpd
  labels:
    app: httpd
spec:
  containers:
    - name: httpd
      image: httpd:2.4.63-alpine
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: httpd
spec:
  type: LoadBalancer
  ports:
    - port: 8001
      targetPort: 80
  selector:
    app: httpd